In [4]:
!python.exe -m pip install --upgrade pip`

/bin/bash: -c: line 1: unexpected EOF while looking for matching ``'
/bin/bash: -c: line 2: syntax error: unexpected end of file


In [5]:
!pip install selenium
!pip install chromedriver_autoinstaller
!pip install pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 13.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 467.7/467.7 kB 14.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.4 MB/s eta 0:00:00


In [3]:
!python -m pip install "pymongo[srv]"==3.11

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 771.7/771.7 kB 6.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 kB 8.0 MB/s eta 0:00:00
  Created wheel for pymongo: filename=pymongo-3.11.0-cp310-cp310-linux_x86_64.whl size=493667 sha256=646dd2d37f31d0268752a957cebae620171dab2bfa0c790106296a06a9db8a56
  Stored in directory: /root/.cache/pip/wheels/df/6e/99/27524029bf53fd025e0d44093d77e4fc0b27c6344acd6f3e86
Successfully built pymongo


In [6]:
from selenium import webdriver

In [7]:
import chromedriver_autoinstaller
from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from pymongo import MongoClient
from IPython.display import HTML
import pandas as pd
import math

In [ ]:
ball1 = []
ball2 = []
ball3 = []
ball4 = []
ball5 = []
ball6 = []
bonus = []
date = []

In [ ]:
driver = webdriver.Chrome()
url = 'https://data.soledot.com/lottowinnumber/fo/lottowinnumberlist.sd'
# driver.get(url)

In [ ]:
driver = webdriver.Chrome()
driver.get(url)
time.sleep(1)

In [ ]:
total = driver.find_element(By.XPATH, '/html/body/div[3]/section[2]/div/form/div/div/div[2]/div[2]/h5/span').text
total= int(total.replace(',', ''))
page = math.ceil(total/20)
page

In [ ]:
for i in range(page):
    nav = driver.find_element(By.XPATH, '/html/body/div[3]/section[2]/div/form/div/div/div[2]/nav')
    lists = nav.find_elements(By.TAG_NAME, 'li')

    remainder = i % 5
    if remainder == 1:
        active = 2
    elif remainder == 2:
        active = 3
    elif remainder == 3:
        active = 4
    elif remainder == 4:
        active = 5
    elif remainder == 0:
        active = 6

    if i != 0:
        lists[active].click()
    time.sleep(0.1)

    for i in range(len(trs)):
        table = driver.find_element(By.ID, 'table1')
        tbody = table.find_element(By.TAG_NAME, 'tbody')
        trs = tbody.find_elements(By.TAG_NAME, 'tr')
        text = trs[i].text
        text = text.split(' ')
        ball1.append(int(text[1]))
        ball2.append(int(text[2]))
        ball3.append(int(text[3]))
        ball4.append(int(text[4]))
        ball5.append(int(text[5]))
        ball6.append(int(text[6]))
        bonus.append(int(text[7]))
        date.append(text[-1])

In [ ]:
table = driver.find_element(By.ID, 'table1')
tbody = table.find_element(By.TAG_NAME, 'tbody')
trs = tbody.find_elements(By.TAG_NAME, 'tr')
for i in range(len(trs)):
    text = trs[i].text
    text = text.split(' ')
    ball1.append(int(text[1]))
    ball2.append(int(text[2]))
    ball3.append(int(text[3]))
    ball4.append(int(text[4]))
    ball5.append(int(text[5]))
    ball6.append(int(text[6]))
    bonus.append(int(text[7]))
    date.append(text[-1])

In [8]:
url = 'mongodb+srv://mnbv7952:hXHFetjGCo06jkTn@cluster0.marjbqu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
client = MongoClient(url)
database = client['lottoAI']
collection = database['lotto']

In [ ]:
lotto_datas = []
for i in range(len(date)):
    lotto_datas.append({
        'ball1':ball1[i],
        'ball2':ball2[i],
        'ball3':ball3[i],
        'ball4':ball4[i],
        'ball5':ball5[i],
        'ball6':ball6[i],
        'bonusball':bonus[i],
        'date':date[i]
    })
result = collection.insert_many(lotto_datas)

## 시계열 예측 딥러닝

In [9]:
documents = collection.find({}, {'_id': 0}).sort('date', 1)
for document in documents:
    print(document)

{'ball1': 4, 'ball2': 5, 'ball3': 7, 'ball4': 18, 'ball5': 20, 'ball6': 25, 'bonusball': 31, 'date': '2003-05-31'}
{'ball1': 1, 'ball2': 20, 'ball3': 26, 'ball4': 28, 'ball5': 37, 'ball6': 43, 'bonusball': 27, 'date': '2003-06-07'}
{'ball1': 9, 'ball2': 18, 'ball3': 23, 'ball4': 25, 'ball5': 35, 'ball6': 37, 'bonusball': 1, 'date': '2003-06-14'}
{'ball1': 1, 'ball2': 5, 'ball3': 13, 'ball4': 34, 'ball5': 39, 'ball6': 40, 'bonusball': 11, 'date': '2003-06-21'}
{'ball1': 8, 'ball2': 17, 'ball3': 20, 'ball4': 35, 'ball5': 36, 'ball6': 44, 'bonusball': 4, 'date': '2003-06-28'}
{'ball1': 7, 'ball2': 9, 'ball3': 18, 'ball4': 23, 'ball5': 28, 'ball6': 35, 'bonusball': 32, 'date': '2003-07-05'}
{'ball1': 6, 'ball2': 14, 'ball3': 19, 'ball4': 25, 'ball5': 34, 'ball6': 44, 'bonusball': 11, 'date': '2003-07-12'}
{'ball1': 4, 'ball2': 7, 'ball3': 32, 'ball4': 33, 'ball5': 40, 'ball6': 41, 'bonusball': 9, 'date': '2003-07-19'}
{'ball1': 9, 'ball2': 26, 'ball3': 35, 'ball4': 37, 'ball5': 40, 'ball6'

In [10]:
import numpy as np

In [11]:
documents = collection.find({}, {'_id': 0}).sort('date', 1)
# 데이터에서 로또 숫자와 보너스 숫자만 추출
data = []

for document in documents:
    lotto_numbers = [
        document.get('ball1'),
        document.get('ball2'),
        document.get('ball3'),
        document.get('ball4'),
        document.get('ball5'),
        document.get('ball6')
        # document.get('bonusball')
    ]
    data.append(lotto_numbers)

data = np.array(data)

In [12]:
len(data)

1100

In [13]:
# 시계열 데이터 생성
def create_sequences(data, sequence_length):
    X = []
    y = []
    for i in range(len(data) - sequence_length):
        X.append(data[i:i + sequence_length])
        y.append(data[i + sequence_length])
    return np.array(X), np.array(y)
# ex) 1회차 -> 2회차, 2회차 -> 3회차, 3회차->4회차

# 시퀀스 길이 설정
sequence_length = 1

X, y = create_sequences(data, sequence_length)
train_size = int(len(X) * 0.9)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]
# 학습용 데이타와 검증용 데이타(최신) 나누기.

print("입력 데이터(X):")
print(X_train)
print("결과값(y):")
print(y_train)

입력 데이터(X):
[[[ 4  5  7 18 20 25]]

 [[ 1 20 26 28 37 43]]

 [[ 9 18 23 25 35 37]]

 ...

 [[ 5 11 18 20 35 45]]

 [[21 22 26 34 36 41]]

 [[ 3 11 14 18 26 27]]]
결과값(y):
[[ 1 20 26 28 37 43]
 [ 9 18 23 25 35 37]
 [ 1  5 13 34 39 40]
 ...
 [21 22 26 34 36 41]
 [ 3 11 14 18 26 27]
 [14 23 31 33 37 40]]


## RNN(순환 신경망)
- 과거의 정보를 사용하여 현재 및 미래의 입력에 대한 신경망의 성능을 개선
- 루프 구조를 통해 신경망은 은닉 상태에 과거의 정보를 저장하고 시퀀스에 대해 연산이 가능
![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fc8w73m%2Fbtq4gaqOlB7%2FEGZo60tRkMI8tymDFRqWX1%2Fimg.png)
- 역전파(backprogation) 과정에서 기울기 소실 or 폭발이 발생.

# LSTM(Long Short-Term Memory)
- LSTM(Long Short-Term Memory)은 순환 신경망(RNN, Recurrent Neural Network)의 한 종류로 시퀀스 데이터를 처리하는 데 주로 사용
- 각 LSTM 셀은 입력 데이터의 시퀀스를 받아들이고, 이전 시간 단계의 상태를 기억하는 능력을 갖춤
- 기억할 것과 잊을 것을 선택해 중요한 정보만 기억하는 것이 핵심(hidden layer의 메모리 셀에 입력 게이트, 망각 게이트, 출력 게이트를 추가하여 불필요한 기억을 지우고, 기억해야할 것들을 정함)

✔ 시퀀스 데이터: 일련의 데이터 포인트가 순서대로 배열된 데이터(ex: 시계열, 텍스트, 음성, DNA 데이터)

### LSTM 파라미터
- input_dim: 입력 데이터의 특성 수
- output_dim: LSTM 층의 출력 차원, 즉 LSTM 셀의 유닛 수(윗 그림에서 A)
- activation: LSTM 셀 내부의 활성화 함수
- return_sequences=True : 각 타임스텝의 출력을 다음 LSTM 레이어에 전달할 수 있어 모델이 더 깊은 시퀀스 패턴을 학습할 수 있다

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
# Dense : 완전히 연결된(fully connected) 뉴런 레이어를 정의할 때 사용
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split

In [16]:
# LSTM 모델 정의
model = Sequential()
model.add(LSTM(100, return_sequences=True, activation='tanh', input_shape=(sequence_length, 6)))
model.add(Dropout(0.2))    # 과적합을 방지하기 위해 학습 중에 랜덤하게 뉴런의 20%를 비활성화
model.add(LSTM(100, activation='tanh')) # 두 번째 LSTM 레이어 추가로 이전 LSTM 레이어의 출력(시퀀스)을 입력으로 받음
model.add(Dense(6)) #출력시 차원을 6으로 지정

optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mse')

# 모델 훈련
model.fit(X_train, y_train, epochs=200, verbose=1, validation_data=(X_test, y_test))

Epoch 1/200
31/31 [==============================] - 7s 53ms/step - loss: 652.6218 - val_loss: 577.8176
Epoch 2/200
31/31 [==============================] - 0s 7ms/step - loss: 456.4043 - val_loss: 379.1297
Epoch 3/200
31/31 [==============================] - 0s 7ms/step - loss: 321.4118 - val_loss: 287.0706
Epoch 4/200
31/31 [==============================] - 0s 8ms/step - loss: 249.5514 - val_loss: 227.0893
Epoch 5/200
31/31 [==============================] - 0s 8ms/step - loss: 199.6691 - val_loss: 182.7321
Epoch 6/200
31/31 [==============================] - 0s 9ms/step - loss: 162.3465 - val_loss: 148.9564
Epoch 7/200
31/31 [==============================] - 0s 8ms/step - loss: 133.9550 - val_loss: 122.7949
Epoch 8/200
31/31 [==============================] - 0s 7ms/step - loss: 111.9820 - val_loss: 102.9366
Epoch 9/200
31/31 [==============================] - 0s 8ms/step - loss: 95.1221 - val_loss: 87.5766
Epoch 10/200
31/31 [==============================] - 0s 9ms/step - loss: 

In [17]:
# 모델 평가
loss = model.evaluate(X_test, y_test, verbose=0)
print(f'Test Loss: {loss}')

Test Loss: 38.99605941772461


In [18]:
# 모델 예측
y_pred = model.predict([[[6, 14, 25, 33, 40, 44]]])
y_pred = np.round(y_pred).astype(int)
y_pred = np.clip(y_pred, 1, 45)

print("예측 값:")
print(y_pred)

1/1 [==============================] - 1s 954ms/step
예측 값:
[[ 7 13 20 26 33 40]]
